service: youtransfer-auth
frameworkVersion: "3"

plugins:
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  tracing:
    lambda: true
    apiGateway: true
  environment:
    LOG_LEVEL: DEBUG
    POWERTOOLS_SERVICE_NAME: auth
    POWERTOOLS_METRICS_NAMESPACE: auth
    CLIENT_ID: !Ref UserPoolClient
    BASE_URL: https://${self:custom.domainName}
    USER_POOL_DOMAIN: ${self:custom.userPoolDomain}


custom:
  domainName: you-tr.click
  userPoolDomain: ${self:service}-${sls:stage}

functions:
  createDeviceAuthorizationRequest:
    handler: device-auth-handler.handleEvent
    events:
      - httpApi:
          method: POST
          path: "/device_authorization"


resources:
  Resources:
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: user-pool-${sls:stage}
        UsernameAttributes: [email]
        AutoVerifiedAttributes: [email]
        Policies:
          PasswordPolicy:
            MinimumLength: 12
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
            RequireUppercase: true
        Schema:
          - AttributeDataType: String
            Mutable: true
            Name: tentant
            StringAttributeConstraints:
              MaxLength: "16"
              MinLength: "2"
          - AttributeDataType: String
            Mutable: true
            Name: tier
            StringAttributeConstraints:
              MaxLength: "16"
              MinLength: "2"
    
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-client-${sls:stage}
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        RefreshTokenValidity: 30
        SupportedIdentityProviders:
          - COGNITO
        WriteAttributes:
          - email
        CallbackURLs:
          - https://${self:custom.domainName}/auth/callback
        DefaultRedirectURI: https://${self:custom.domainName}/auth/callback
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthFlows:
          - code
        AllowedOAuthScopes:
        - openid
        UserPoolId: !Ref UserPool

    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        Domain: ${self:custom.userPoolDomain}
        UserPoolId: !Ref UserPool

    UserPoolId:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /youtransfer/${sls:stage}/userPoolId
        Type: String
        Value: !Ref UserPool

    UserPoolClientId:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /youtransfer/${sls:stage}/userPoolClientId
        Type: String
        Value: !Ref UserPoolClient